# Generated by Django 4.2 on 2025-07-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='p_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='p_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='p_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='s_time',
            field=models.CharField(max_length=100),
        ),
    ]
